### ISSUE TITLE
name of the repo; readme

### ISSUE THREAD

**Issue by Alexey-T** [GuvaCode/Galcon4Ray#1]
name of the repo: why not full game title, so web search will find it better? GalaxyConquest_for_RayLib

readme:
`Galaxy Conquest strategy game using raylib and fpc compiler(Lazarus ide)` --> 
`Galaxy Conquest strategy game, built using RayLib and FPC compiler (Lazarus IDE)`

**Comment by GuvaCode** [comment]
fixed. tnx
