### ISSUE TITLE
Compilation error on Windows 64b

### ISSUE THREAD

**Issue by Lulu04** [GuvaCode/Galcon4Ray#3]
Hi Guva,
thanks you for your game.
I try to compile the project on Windows 10 with Lazarus 2.2.6 and I have the following compilation error:
**Identifier not found "Vector2AngleDeg" in unit UGame, line 375**

any idea?

**Comment by GuvaCode** [comment]
yes, this function add to trunck version. 

в  рейлиб какой-то косяк 
sorry for my eng

uses this

function Vector2AngleDeg(v1, v2: TVector2): single;
begin
  result := arctan2(v2.y - v1.y, v2.x - v1.x) / DEG2RAD;
end;

**Comment by Lulu04** [comment]
It work, thank you.
Nice game :)
